spring:
  kafka:
    props:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      producer:
        value-serializer: ru.practicum.avro.serializer.GeneralAvroSerializer
      consumer:
      value-deserializer: ru.practicum.avro.deserializer.SensorEventDeserializer
    topics:
      hub-topic-name: telemetry.hubs.v1
      sensor-topic-name: telemetry.sensors.v1
      snapshots-topic-name: telemetry.snapshots.v1