server:
  port: 0

grpc:
  client:
    hub-router:
      address: "static://localhost:59090"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analyze
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      snapshot-value-deserializer: ru.practicum.avro.deserializer.SensorsSnapshotDeserializer
      snapshot-group-id: snapshots-analyzer-group
      hub-event-value-deserializer: ru.practicum.avro.deserializer.HubEventDeserializer
      hub-event-group-id: hub-event-group

    topics:
      hub-topic-name: telemetry.hubs.v1
      snapshots-topic-name: telemetry.snapshots.v1